### ISSUE TITLE
Heart of Avelorn quest can fail without backup

### ISSUE THREAD

**Issue by VittorioBianco** [chadvandy/cbfm_wh3#83]
The quest is issued, then dropped, presumedly when Alarielle goes for the shine of khaine and Tyrion cannot get the item.

**Comment by Harmandodelavega** [comment]
Apparently also dropped when you ally with Avelorn (who I presume  owned the settlement)

**Comment by pigwithsnoot** [comment]
This bug might have been fixed by CA in patch 2.2.

CAMPAIGN
Legendary Lord quests granting unique items will now grant the ancillary if the mission is cancelled.

**Comment by Harmandodelavega** [comment]
should be fixed by 2.2

**Comment by missj4** [comment]
Has not been fixed, multiple people reporting the bug still exists on steam forum as of Nov. 4

**Comment by Harmandodelavega** [comment]
I'm not sure those commenters were playing a fresh campaign

**Comment by missj4** [comment]
I did play a brand new fresh campaign(because of update), and had it occur. Avelorn has the gate but it didnt give me the item. I can't find the mission, no reference to it anywhere, the item is missing/never granted. Even used console to confederate Avelorn and didn't get it.
